### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by Nalha** [guiguilechat/JCELechat#26]
Some of your modules use things from fr.lelouet.tools but don't have a dependency on that module in their pom.

For example Blueprint uses import fr.lelouet.tools.settings.yaml.YAMLTools; but the SDE-Industry pom.xml does not have a lelouet dependency listed.

Found and added separately from your root pom to my project tho.

**Comment by glelouet** [comment]
the dependency is in the sde-raw, which is in the dependencies of sde-industry.

**Comment by Nalha** [comment]
But raw is optional and Industries does not compile without it

**Comment by guiguilechat** [comment]
I moved the dependency from sde/raw to sde/ level, therefore all the children of sde should have it in deps. Is it okay ?

**Comment by Nalha** [comment]
Cool yea that should solve the problem :)
