### ISSUE TITLE
Yaml missing stats

### ISSUE THREAD

**Issue by Nalha** [guiguilechat/JCELechat#27]
Apparently Tracking Computer II seems to be missing its CPU value in the included yaml files, any idea what might have caused this?

https://github.com/guiguilechat/JCELechat/blob/master/model/sde/SDE-Items/src/generated/resources/SDE/items/module/TrackingComputer.yaml

Row 245 should be "Cpu:"

Edit: Looking closer at it there are CPU values missing all over the place.

**Comment by guiguilechat** [comment]
hmm line 428775 seems correct for the definition of 35 CPU to this module.

**Comment by guiguilechat** [comment]
got it, it's because CPU has sometimes float value so I use value float all of the time. But sometimes it's value int.

**Comment by Nalha** [comment]
Ah, ccp consistency strikes again ;)

**Comment by guiguilechat** [comment]
if you look at dgmTypeAttribute line 430686 you'll notice it's     valueFloat: 35.0

now line 430353     valueInt: 55

It's not ccp consistency, it's me who made fast code and did not consider the case where the attribute is set float values and integer values somewhere else.

**Comment by guiguilechat** [comment]
same issue with maxvelocity too (was not present in eg rockets )

**Comment by guiguilechat** [comment]
Thank you, BTW

**Comment by Nalha** [comment]
No problem and a big thanks to you for providing this lib, it saved me a ton of time setting up a new project!

**Comment by Nalha** [comment]
@guiguilechat hey I think I found another one, there are no MaxVelocityBonus on any module except for MassEntanlers.

**Comment by guiguilechat** [comment]
can you give an example, if possible with an ESI link for that item ?

The attribute id from the SDE is 2603 . in the dgmtypeattribute.yaml there are only 5 entries
Those are 

 - https://esi.evetech.net/v3/universe/types/49099 module "mass entangler"
 - https://esi.evetech.net/v3/universe/types/12305 skill "drone navigation"
 - https://esi.evetech.net/v3/universe/types/43703 skill "ice harvesting drone specialization"
 - https://esi.evetech.net/v3/universe/types/40572 skill "light fighters"
 - https://esi.evetech.net/v3/universe/types/22541 skill "mining drone specialization"

Which one is there that are not present ?

**Comment by Nalha** [comment]
Oh apparently nanofibers have its speed bonus under Attribute 1076, is that supposed to be named ImplantBonusVelocity?

**Comment by guiguilechat** [comment]
example ?

**Comment by Nalha** [comment]
Found it on esi and in the sde now

https://esi.evetech.net/v3/universe/types/2605
"attribute_id": 1076,
"value": 9.5

dgmAttributeTypes.yaml
-   attributeID: 1076
    attributeName: implantBonusVelocity

**Comment by Nalha** [comment]
but that is a damn weird choice from CCP
